name: Run CICD
on:
  push:
    branches:
      - main
  pull_request:

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install dependencies
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - run:
            pip install -r requirements.txts

        - name: Run tests
          run: echo "Running tests"
        
        - name: Deploy to staging
          run: echo "Deploying to staging"

       
