name: Run CICD
on:
  push:
    branches:
      - main
  pull_request:

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install dependencies
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - run:
            pip install -r requirements.txt

        - name: Run tests
          run: echo "Running tests"
        
        - name: Deploy to staging
          run: echo "Deploying to staging"

        - name: Check PR Workflows
          run: |
            echo "🔍 Fetching the latest 5 open PRs..."
            PRS=$(gh pr list --state open --limit 5 --json number --jq '.[].number')
  
            if [[ -z "$PRS" ]]; then
              echo "✅ No open PRs found. Skipping..."
              exit 0
            fi
  
            FAILED=0
            for PR in $PRS; do
              echo "🚀 Fetching latest workflow run for PR #$PR..."
              RUN_ID=$(gh run list --branch refs/pull/$PR/head --limit 1 --json databaseId --jq '.[0].databaseId')
  
              if [[ -z "$RUN_ID" ]]; then
                echo "⚠️ No previous workflow found for PR #$PR. Skipping..."
                continue
              fi
  
              echo "🔄 Re-running workflow for PR #$PR (Run ID: $RUN_ID)..."
              gh run rerun $RUN_ID
  
              sleep 10  # Give some time for workflow to start
  
              echo "🔍 Checking workflow status for PR #$PR..."
              PR_STATUS=$(gh run list --branch refs/pull/$PR/head --limit 1 --json conclusion --jq '.[0].conclusion')
  
              if [[ "$PR_STATUS" == "failure" || "$PR_STATUS" == "cancelled" ]]; then
                echo "❌ PR #$PR workflow failed!"
                FAILED=1
              else
                echo "✅ PR #$PR workflow passed!"
              fi
            done
  
            if [[ "$FAILED" -eq 1 ]]; then
              echo "❌ One or more PR workflows failed. Failing main branch workflow."
              exit 1
            else
              echo "✅ All checked PR workflows are successful!"
            fi
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
