name: Run CICD
on:
  push:
    branches:
      - main
      - feature-*
  pull_request:

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install dependencies
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - run:
            pip install -r requirements.txt

        - name: Run tests
          run: echo "Running tests"
        
        - name: Deploy to staging
          run: echo "Deploying to staging"

        - name: notify main is green [main/base branch]
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            main_workflow_status=$(gh run list --branch main --workflow cicd.yaml --json status --jq '.[0].status')
            if [ "$main_workflow_status" != "completed" ]; then
              echo "Main branch workflow is not completed. Failing the step."
              exit 1
            fi
            if [ "$(gh run view --branch main --workflow cicd.yaml --json conclusion --jq '.conclusion')" != "success" ]; then
              echo "Main branch workflow failed. Failing the step."
              exit 1
            fi
            # gh pr list --state open --json number | jq -r '.[].number' | while read pr; do
            #   gh workflow run cicd.yaml --ref refs/pull/$pr/head
            # done
            # echo "Triggered workflow on all open PRs"
