name: Run CICD
on:
  push:
    branches:
      - main
  pull_request:

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install dependencies
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - run:
            pip install -r requirements.txt

        - name: Run tests
          run: echo "Running tests"
        
        - name: Deploy to staging
          run: echo "Deploying to staging"

        - name: notify main is green [main/base branch]
          run: |
            gh pr list --state open --json number | jq -r '.[].number' | while read pr; do
            gh workflow run cicd.yaml --ref refs/pull/$pr/head
            done
            echo "Triggered workflow on all open PRs"