name: Run CICD
on:
  push:
    branches:
      - main
      - feature-*
  pull_request:

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install dependencies
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - run:
            pip install -r requirements.txt

        - name: Run tests
          run: echo "Running tests"
        
        - name: Deploy to staging
          run: echo "Deploying to staging"

        - name: Get latest workflow run status on main
          id: check_main_status
          run: |
            MAIN_WORKFLOW_STATUS=$(gh run list --branch main --limit 1 --json conclusion --jq '.[0].conclusion')
            echo "Latest main workflow status: $MAIN_WORKFLOW_STATUS"
        
            if [[ "$MAIN_WORKFLOW_STATUS" == "failure" || "$MAIN_WORKFLOW_STATUS" == "cancelled" ]]; then
                echo "❌ Main branch workflow failed, stopping PR workflow."
                exit 1
            fi
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
